### PR TITLE
Removed limit from sa-learn mbox size

### PR DESCRIPTION
**Pull request by jbahillo**
Added needed mbox parameter to be able to processs mbox format
Added small text specifying expected mailbox format

### CODE REVIEW

**Comment by sixstone-qq** [comment]
:+1:

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Comment by jacalvo** [comment]
Jenkins retest this please.

**Pull request merged**
