### PR TITLE
Better error when editing user with empty first or last name

### PR DESCRIPTION
**Pull request by javierag**

### CODE REVIEW

**Comment by javierag** [comment]
Error in jenkis infraestructure:
stderr: fatal: ambiguous argument 'dba6f8dc7f247748f34513764385951f591e0815^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

**Comment by javierag** [comment]
Jenkis retest this please.

**Comment by jacalvo** [comment]
Are you sure this does not introduce any regression? I think the allow empty was to avoid errors when editing special users like Guest that had no first or last name...

**Comment by papajulio** [comment]
@jacalvo I had to fix the tests because of that, it makes compulsory to write a First Name and Last name to the Guest user when activating it, but I don't see any major issue on that as it warns you clear about it and doesn't crash like now in the other cases. See https://github.com/Zentyal/qa/commit/282f3d5c110c5ad837a532c6eaddeaf6d14394a9

**Comment by jacalvo** [comment]
Ok, for me it's a bit odd the need to set a last name to guest... but if this prevents other worse problems, let's merge it...

**Pull request merged**
