### PR TITLE
Remove Clone::Fast dependency and use Storable dclone

### PR DESCRIPTION
**Pull request by idstein**
As stated by the author of Clone::Fast is deprecated ( https://github.com/hallta/Clone-Fast#deprecation ).

In addition to that, it is unstable and incompatible with Perl API since 5.11 as shown (http://matrix.cpantesters.org/?dist=Clone-Fast%200.97).

As a replacement I propose to use (as a intermediate solution) Storable dclone. It is part of Perl core modules since Perl 5.8. And might not be affected by a memory leak, as so reasoned within the history for Clone::Fast (http://search.cpan.org/~jjore/Clone-Fast-0.96/lib/Clone/Fast.pm#HISTORY).

The slight performance decrease might be arguable, but as long as the Clone::Fast is not maintained and Clone is not endurable (rebooting a Zentyal server might not be a good maintenance advice), I would advise to stay with Storable dclone.

An alternative would be to benchmark Clone::PP and see how stable this module is.

Cheers,
π

### CODE REVIEW

**Comment by papajulio** [comment]
Can one of the admins verify this patch?

**Comment by papajulio** [comment]
Can one of the admins verify this patch?

**Comment by jacalvo** [comment]
Jenkins this is ok to test.

**Comment by idstein** [comment]
Also the libclone-fast-perl package does not seem to be longer maintained for Debian based systems https://packages.debian.org/search?keywords=libclone-fast-perl

So this is also an open issue to support 14.10+ Ubuntu systems.

**Comment by papajulio** [comment]
Please @idstein can you run the unit tests and check that they are runnig properly? 

You can use docker to do so if you don't have a proper dev-enviroment setted up or don't want to pollute your machine. Check the folder extra/scripts/docker and the script extra/scripts/zentyal-unit-tests

Thanks!

**Comment by jacalvo** [comment]
Closing this as libclone-fast-perl was replaced by libclone-perl, if you still think there are good reasons to switch to Storable::dclone, please don't hesitate to open a new PR for that. Thanks!

**Pull request closed without merging**
