### PR TITLE
Changed import to TryCatch instead of TryCatch::Lite

### PR DESCRIPTION
**Pull request by tomasz89**
Fixes adding of the gateway to Zentyal when it's acting as the PPPoE gateway as the script fails to run due to using a Perl module that is unavailable.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@tomasz89 @brunolorente: Any news about old TryCatch::Lite package to TryCatch like other parts?

https://github.com/zentyal/zentyal/search?q=TryCatch%3A%3ALite&unscoped_q=TryCatch%3A%3ALite

**Comment by tomasz89** [comment]
Hi, I upgraded to 6.1 yesterday only to have the same old bug crop up and broke a remote site, requiring a visit. It's not been fixed. Neither has the Squid/localhost bug that I provided a patch for either. What more can I do except provide a problem description, solution, and patches?

**Comment by brunolorente** [comment]
Hi @tomasz89

I'm going to merge to master the commits b721c719e3dafef6b6a10b11e05608b9d1dac068 and 5ee41e649cf330b72dca816288a7c2f93979dec5 but not c07446f4f40c56a2afe2fa24c914ddbe67c76222

As I told before, the last one requires a more complex fix.

On the other hand, my apologizes, in the last months we have been overwhelmed by work.

**Comment by brunolorente** [comment]
Hi @tomasz89 and @Neustradamus 

I merged to master the commits b721c719e3dafef6b6a10b11e05608b9d1dac068 and 5ee41e649cf330b72dca816288a7c2f93979dec5 but not c07446f4f40c56a2afe2fa24c914ddbe67c76222
As I told before, the last one requires a more complex fix.

On the other hand, my apologizes, in the last months we have been overwhelmed by work.

**Pull request closed without merging**
