### PR TITLE
Address #1822

### PR DESCRIPTION
**Pull request by jacalvo**

### CODE REVIEW

**Comment by unquietwiki** [comment]
@jacalvo Thanks for opening this. Trying to get a setup going wherein I can better help you validate this will all work. The underlying bits already work: it's the "I'm not a Perl dev" part. :octocat:

**Comment by unquietwiki** [comment]
@jacalvo Hey, I can't re-base to work on this due to #1828 ; please take a look when you can. Thanks!

**Comment by jacalvo** [comment]
now this is updated with all the new changes from master

**Comment by unquietwiki** [comment]
Huzzah! I’ll do more stuff next week as able to verify the Perl script changes.

Michael Adams
https://unquietwiki.com/

**Comment by unquietwiki** [comment]
@jacalvo How do you want to integrate **dnsupdate.py** with this? Permission to include the file? Download to /usr/local/bin at install time?

Also, regarding IPv6 zones in BIND9, https://www.oreilly.com/library/view/dns-and-bind/9781449308025/ch01.html may be good guidance for this.

**Comment by Neustradamus** [comment]
@unquietwiki, it is now @brunolorente, can you see for add an option to enable or disable IPv6 feature in webadmin?

**Comment by Neustradamus** [comment]
@brunolorente: Any news?

**Comment by Neustradamus** [comment]
@brunolorente: What do you think about this PR and master branch?
IPv6 is really important now... Several providers have only IPv6...

**Comment by Neustradamus** [comment]
@brunolorente: Several years after, any news?

**Pull request closed without merging**
