### PR TITLE
First try to recover listen_interal_ifaces_only on samba

### PR DESCRIPTION
**Pull request by jbahillo**
Asking merge for initial test on jenkins, but further tests required

### CODE REVIEW

**Comment by jbahillo** [comment]
This should be ready to merge

**Comment by jbahillo** [comment]
Jenkins retest this please

**Comment by jbahillo** [comment]
Jenkins retest this please

**Comment by jbahillo** [comment]
Jenkins retest this please

**Comment by jacalvo** [comment]
I would prefer to not change the default behavior in 4.0 if configuration in /etc/zentyal is not customized, so what I would do to be less invasive to what is working is, by default not write extra options to smb.conf, but if a key listen_all_ifaces = No is added at /etc/zentyal/samba.conf is added, then the listen_internal_ifaces is taken into account and the two lines are written in smb.conf, are you ok with that?

**Comment by jbahillo** [comment]
Hello:
I think that as listen_external = yes is the default behaviour  and this has the same practical effects as current default behaviour (makes samba to listen on any physical interface) this should not be invasive.

The only case where this might hit is when a custom stub for smb.conf.mas has been created, but in such a case it would be hitting anyway (If I'm not missing anything)

**Comment by jacalvo** [comment]
Listening on the list of the zentyal interfaces is not the same as listening in 0.0.0.0, that's what you are missing ;)

**Pull request merged**
