### PR TITLE
Address #1822

### PR DESCRIPTION
**Pull request by unquietwiki**
This looks like a big change, but there's really only 3 things going on....

- Minor changes to allow IPv6 to work again.
- Removed localization that said IPv6 was being disabled: a lot of changes happened here.
- Release 1.0 of https://github.com/novnc/noVNC was synced in: this may have not been necessary, but seemed important for the other bug.

### CODE REVIEW

**Comment by jacalvo** [comment]
Could you remove the extra/novnc part? This was and old code from the time novnc was not packaged into ubuntu, now we just depend on the novnc package and we do not ship our own novnc code. I've already removed it from master to avoid confusion.

Also, the changes in the .po files are not necessary because they are automatically updated from the source before release. They are harmelss but it would be great to get rid of them so the PR is shorter and we can review the real changes easily.

Thanks!

**Comment by unquietwiki** [comment]
I can do that. The PO files, I did notice an inconsistency in what was
presented. Some files had 2 sections; some, 1.

**Comment by unquietwiki** [comment]
@jacalvo Alright, so I downloaded the original PO files & put those back in here. Still counts as a whitespace change for some reason: if you check that option on here, it should be easier to see what all got deleted from nuking noVNC & changed for the IPv6 stuff.

**Comment by jacalvo** [comment]
As the diff was still very big I've done some cleaning and pushed your changes to a new unquietwiki-master branch and created a new #1827 PR. If you want to do more changes feel free to fork that branch or start with a clean fork of master and cherry-pick the 
e311188 commit to create your own PR.

Before testing/merging, would be also great to know what kind of tests have you done already, if any :)

**Pull request closed without merging**
